### PR TITLE
v1.0.1 Fix torrent progress bar and ETA issue

### PR DESCRIPTION
**Pull request by AnonTester**

### CODE REVIEW

**Comment by basilgello** [comment]
Hi @AnonTester! Thanks for the patch! Let me build the latest nightly and do some testing of this PR tonight.

Do you have screenshots of what was wrong with 1.0.0? I used debian-transmission on buster and it worked fine there.

**Comment by AnonTester** [comment]
I don't have a screenshot, but the progress bar of torrents on the main gui wasn't working (always at 0) but fine in detail view. Also, stalled torrents without an ETA caused a value exception in detail view. With the fix those are showing an eta of N/A now.

**Comment by basilgello** [comment]
> I don't have a screenshot, but the progress bar of torrents on the main gui wasn't working (always at 0) but fine in detail view. Also, stalled torrents without an ETA caused a value exception in detail view. With the fix those are showing an eta of N/A now.

OK, I see you changed CRLF in torrent.py so the diff became that big. I will now format the code using google's yapf and incorporate your fix for testing.

**Comment by AnonTester** [comment]
ah yeah, did a dos2unix on that file while looking into it, but didn't actually change anything in the file itself.
Re the ETA, I'm using Transmission 3.00-18 on a Synology, not sure if there was a change to how ETAs are reported which may result in the value error and you didn't. Buster still has 2.94 from what I can see.

**Comment by AnonTester** [comment]
the changed import line in the utils.py comes from a 2to3 run I did a little while ago.

**Comment by basilgello** [comment]
Can you please rebase your commit on top of my recent commit? Here is the cleaned patch: 

[0001-v1.0.1-Fix-torrent-progress-bar-and-ETA-issue.patch.txt](https://github.com/basilgello/Transmission-Control-Panel/files/5213058/0001-v1.0.1-Fix-torrent-progress-bar-and-ETA-issue.patch.txt)

**Comment by basilgello** [comment]
@AnonTester can you please try this new revision? I also fixed the KeyError thrown inside updateTorrent() after user deletes the torrent from Transmission.

**Comment by AnonTester** [comment]
@basilgello Working fine on my system.

**Comment by AnonTester** [comment]
Please merge when you've got the time. Thanks.

**Comment by basilgello** [comment]
Sure! I am waiting for alpha2 tag which is delayed due to cpp17 commit breaking many addons.

**Pull request merged**
